#!/bin/sh
############# EASY_APM BASIC ENV SET ##############################
EASY_APM_DIR="/usr/local/src/EASY_APM"
source $EASY_APM_DIR/EASY_APM_ENV.sh
##################################################################


rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_APR
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_APR_UTIL
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_CMAKE
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_HTTPD_2_4
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_MARIADB_10_0
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_PHP_5_4
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_PROFTPD


rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LUA
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_PCRE


rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_CURL
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_EXPAT
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_FREETYPE2
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_GD
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_ICONV
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBJPEG
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBMCRYPT
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBPNG
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBTIFF
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBXML2
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_LIBXSLT
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_MCRYPT
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_MHASH
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_ZENDGUARD_54_32
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_ZENDGUARD_54_64
rm -fr $EASY_APM_SOURCE/$EASY_APM_APP_ZLIB
