#!/bin/sh
############# EASY_APM BASIC ENV SET ##############################
EASY_APM_DIR="/usr/local/src/EASY_APM"
source $EASY_APM_DIR/EASY_APM_ENV.sh
##################################################################


tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_APR.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_APR_UTIL.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_CMAKE.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_HTTPD_2_4.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_MARIADB_10_0.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_PHP_5_4.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_PROFTPD.* -C $EASY_APM_SOURCE/


tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LUA.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_PCRE.* -C $EASY_APM_SOURCE/


tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_CURL.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_EXPAT.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_FREETYPE2.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_GD.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_ICONV.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBJPEG.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBMCRYPT.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBPNG.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBTIFF.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBXML2.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_LIBXSLT.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_MCRYPT.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_MHASH.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_ZENDGUARD_54_32.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_ZENDGUARD_54_64.* -C $EASY_APM_SOURCE/
tar xvpfz $EASY_APM_SOURCE/$EASY_APM_APP_ZLIB.* -C $EASY_APM_SOURCE/
