#!/bin/sh
############# EASY_APM BASIC ENV SET ##############################
EASY_APM_DIR="/usr/local/src/EASY_APM"
source $EASY_APM_DIR/EASY_APM_ENV.sh
##################################################################


cd $EASY_APM_SOURCE/$EASY_APM_APP_CMAKE
./configure --prefix=$DEST_DIR/cmake
make
make install
